#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmakeLnInclude myInterfacialModels
wmakeLnInclude myInterfacialCompositionModels
wmake $targetType myPhaseSystems
wmake $targetType myInterfacialModels
wmake $targetType myInterfacialCompositionModels
myReactingTwoPhaseEulerFoam1D/Allwmake $*

#------------------------------------------------------------------------------
