#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wclean libso myPhaseSystems
wclean libso myInterfacialModels
wclean libso myInterfacialCompositionModels
myReactingTwoPhaseEulerFoam1D/Allwclean

#------------------------------------------------------------------------------
